### ISSUE TITLE
Config.json not read in 0.9.1 release

### ISSUE THREAD

**Issue by bencawkwell** [JapaMala/armok-vision#28]
Since I am still using the 0.40.24 release of dwarf fortress with dfhack 0.40.24-r5, I first tried armok-vision 0.9.0. After playing around a bit I noticed the Config.json, and tweaked the values for the following:

- drawRangeSide
- drawRangeUp
- drawRangeDown

I thought I would try 0.9.1 since I was missing tree foliage, but noticed Config.json was not included in the zip? I created the file anyway but changing the values for the above properties has no impact. I have not tested any other configuration options other than the above.

My next step is to update dwarf fortress and dfhack, and retest (since the foliage was still missing and I should blatantly be using the latest version of dfhack!), but since Config.json was not included in the 0.9.1 release I wondered whether its support might have been removed intentionally?

I will update this ticket once I have tested with the correct version of dfhack, my current setup is everything running in an ubuntu docker container, so I am using the linux 32bit version of armok-vision.

BTW really cool project, I am really excited to play with it more with my fort in progress!

**Comment by JapaMala** [comment]
Config.json is not included because it is created fresh when you try
running Armok Vision without it. That way if you mess something up, you can
go back to defaults.
On 25-May-2016 12:26 AM, "Ben Cawkwell" <notifications@github.com> wrote:

Since I am still using the 0.40.24 release of dwarf fortress with dfhack
0.40.24-r5, I first tried armok-vision 0.9.0. After playing around a bit I
noticed the Config.json, and tweaked the values for the following:

   - drawRangeSide
   - drawRangeUp
   - drawRangeDown

I thought I would try 0.9.1 since I was missing tree foliage, but noticed
Config.json was not included in the zip? I created the file anyway but
changing the values for the above properties has no impact. I have not
tested any other configuration options other than the above.

My next step is to update dwarf fortress and dfhack, and retest (since the
foliage was still missing and I should blatantly be using the latest
version of dfhack!), but since Config.json was not included in the 0.9.1
release I wondered whether its support might have been removed
intentionally?

I will update this ticket once I have tested with the correct version of
dfhack, my current setup is everything running in an ubuntu docker
container, so I am using the linux 32bit version of armok-vision.

BTW really cool project, I am really excited to play with it more with my
fort in progress!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/JapaMala/armok-vision/issues/28>

**Comment by bencawkwell** [comment]
Updated everything, and after a few more tests saw that Config.json was created, and updating it does indeed work.

It was most probably not created before because I am doing weird things like executing the Armok Vision.x86 binary from a different directory, and to add to the complexity using different users inside a docker container. Sorry to have bothered you, I will close this issue.
