### ISSUE TITLE
Proper VR support.

### ISSUE THREAD

**Issue by JapaMala** [JapaMala/armok-vision#34]
There was an issue about this already, which has been closed, but this is more about planning how it will be implemented.

Two things need to be decided:

How will it be enabled? Should it be automatic as long as a headset is connected, or should a hotkey switch to VR mode, while the default remains 2D?

How to handle third person mode? I'm picturing having the currently working level around chest height, for standing mode, or desk height for sitting mode. And while there's plenty of ways of doing movement in first person, how will things be handles in third person?

**Comment by PeridexisErrant** [comment]
My proposals:

- Just use true headset height.  This is the default, and anything else invites bugs in my experience.
- On start, if a headset is connected use VR mode.  Otherwise, normal mode - no need for options most people can't use anyway.
- Just don't have third person mode in VR until everything else works.  After that:

  - For movement, I'd just use teleport again - if the far terrain has a collision mesh, that would work fine.
  - Zooming could be handled in many ways, such as "pinch to zoom" while holding down the triggers.

Other things to do, in order:

- [ ] @JapaMala implement startup toggle for VR or normal mode.  Ideally this results in a static bool somewhere that everything else can check.
- [ ] disable unit lights in VR mode
- [ ] @JapaMala make stairs/ramps/trees/terrain climbable (see #33 for notes), possibly all collision geometry
- [ ] (me?) add skins to controllers (left=flaming torch/light source, right=pick/decorative only)
- [ ] (me) testing, testing, testing (I'll have to track down a large community fort
- [ ] (me) make promotional video
- [ ] release!
- [ ] third person mode, later

**Comment by JapaMala** [comment]
Negative. I see no reason why not so support third person VR mode.

How else can you walk through your fortress like a model?

**Comment by JapaMala** [comment]
After some messing around, I've found that there are some issues with forward rendering

 * Ambient Occlusion is being applied onto the hidden geometry above the current layer
 * MSAA messes up the tile borders, giving white lines between all the tiles, which is ugly as hell.
 * Unit lights are no longer viable.

I'd probably make it a user option, and even then, I won't be using MSAA with forward rendering.

**Comment by JapaMala** [comment]
Okay, I made a user option for deferred rendering, which you can build and try out. I also left vertex lit in there, but that's terrible, so probably shouldn't be kept in.

Now I just need to add a toggle for ambient occlusion, then the decision will be up to the user.

**Comment by JapaMala** [comment]
@PeridexisErrant I made it automatically start in VR mode if it's available, otherwise it starts in normal mode. There's already a global variable for checking if the curent VR setup is either OpenVR or None, so I'm using that.

Right now, the VR rig is set to start centered on the current DF view, but there's no way to move it. Probably the best way would be to press a button on one of the controllers and drag the world around. That would probably best be coded by somebody with actual access to the controllers.

I also have a system in place now for switching between camera rigs, and it keeps the same camera, so we can have a third person camera rig, and a first person rig, and the player can easily swap between them. Possibly by pointing at tile and pressing a button, making him shrink to normal size and teleport there.

**Comment by PeridexisErrant** [comment]
I'll ask my friend to help out again, but here's some observations:

- If I start with a headset plugged in but inactive, AV launches SteamVR but does not use VR mode (???)
- if I start with SteamVR running, the distant terrain renders and I can look around... but the local terrain doesn't render.  (also no movement or zoom controls, but we knew that)
- in-game menus should be available in VR and bound to the menu button
- full-world movement and zooming controls are non-obvious, I'll think and discuss with my friend

@JapaMala, if you could work on the following that would be great:

- if Armok Vision is in VR mode, render path *must* be forced to `forward` or things get really bad
- likewise unit lights need to be disabled in VR mode
- add the `climbable` script mentioned in #33 to all terrain, trees, and buildings (it would be nice if buildings and stairs had collision too)
- maybe just force first-person mode in VR for now?  Zooming out can be done later...

I will try my best to be helpful but with no experience in Unity or C# it's hard to do much more than testing with Vive hardware!

**Comment by JapaMala** [comment]
Testing with vive hardware is good enough.

**Comment by JapaMala** [comment]
One thing you can try: change the down draw distance to 33 or more, and see if anything is rendered when you go into VR mode.

**Comment by PeridexisErrant** [comment]
Ah!  Yes, that worked - I can see the fort terrain now.

Framerate is very low though, and when I VR mode I can't even use the mouse to zoom into first-person mode.

**Comment by JapaMala** [comment]
Yeah, first person key is now c, rather than zooming in. Zooming in gives the floating view.

Can you check the framerate difference between forward and deferred rendering? that can be changed realtime.

**Comment by PeridexisErrant** [comment]
Unfortunately VR mode seems to block keyboard and mouse input entirely - I can't zoom *at all*, and pressing `c` (or other keys) doesn't do anything.  The only exception is that `Esc` brings up the menu, which accepts mouse input.

I get 20 to 30 FPS in either mode, which is obviously insufficient for VR (steady >=90).

Other graphics issues:  there is no skybox (just blackness), and the vertical faces of non-fortress terrain have substantial flickering.

**Comment by JapaMala** [comment]
Yeah, VR mode turns off the monitor camera rig, which is what accepts most of the keyboard input.

Anyway, I pushed a new commit that puts you in first person mode, in the center of the DF view. I think this also matches the ingame cursor if there's no menus open.

I also added the climb script to all terrain colliders, so that needs to be tested.

The FPS will be slow as long as terrain updates are coming in from DF, so see if it gets better after the updates finish.

**Comment by PeridexisErrant** [comment]
Nice, I'm in first-person mode now!  :smile:

The catches:
- Teleporting is not working for some reason - given that I can see the arc in red rather than green, I'd guess the meshes aren't being set as valid teleport targets or something.
- I started in midair, five or so levels above ground.
- Due to the above points, I haven't been able to test the climbing yet.  :cry:
- FPS is consistently 10-20, up to 25 after all terrain updates.

**Comment by JapaMala** [comment]
Oh, you need a script for valid targets? I did not know that. I'll add it
and update it.

**Comment by gigafunk** [comment]
Ok, game on. It sucks work is crazy crazy now and I havent had much time. 
I couldnt get it to render anything in unity, the tracking moved the grey horizon around properly, but no armok vison in there. A compile and run did the trick though and I got the no keyboard input I am stuck mode, as described above.  Seems like next up is to got the armok map draggin around and zoom controls.  I only have saturday off this weekend, and if i get a strange mood ill hammer away at it. My level is script-kiddy, though, lol, so dont expect to much progress! and did a fair amount of cut and paste scripting in ultima online(botting) back in the day, but have been dodging learning to program properly for a loooong time now, and its time, so i am working my way up the tutorial tree now, and am committed.  Working with the controllers is seems pretty easy  for basic stuff so i think a can at least get zoom going! 

Pinch zoom? Thats my angle unless you guys object.

**Comment by PeridexisErrant** [comment]
Welcome!  I'm sub-script-kiddie with C\# or Unity more generally, though decent in Python, so it's lovely to have more contributors.

For locomotion, we're supporting teleportation (press trackpad, aim parabola, release) and climbing (hold grip button with controller in surface).  Pinch-to-zoom - my favoured plan for zooming too - should therefore (probably) use the triggers.

The other thing which would be awesome would be to skin the controllers with a little minecraft-style pickaxe and torch, just for fun (and a reliable lightsource underground); that may not be your thing though!

**Comment by gigafunk** [comment]
Ok, after getting a few hours to sit down with it and check it out, whew its hard lol!

My first goal will be to have a vive button center the view on the adventurers spot in adventure mode.

cause right now, i cant seem to get my veiw to the adventurer, im just buried in the ground far from him.

my lynda.com just got activated, so i am going to eat a few unity 3d tutorials and revisit adventure mode, now i am off to get a fort going to try out fortress mode

**Comment by PeridexisErrant** [comment]
Alright, I' just tried f4ec2b2e96cd9e5b66fb21f7e28d19ea426c90f0 and things are going pretty well!

- This time, instead of mid-air I appeared *underground*, in unmined tiles.  Perhaps starting in VR mode could start by dropping the viewpoint from the top of the map, to ensure that movement is possible?
- Grabbable terrain, for climbing, is mostly working.  I was constantly snapped back to ground level though, but I suspect that might be an issue caused by invalid positioning.
- Teleporting still doesn't work, though this time it might be due to the location.
- I'm not sure if falling is implmented.  TODO: check

Performance was substantially better than last time; and easily made it up to 90FPS when I dialled the render distance down.  Doing this automatically would be nice.  I suspect substantial geometry culling would also be possible, and probably be very helpful.

I'll try again in another location and report back later.

**Comment by JapaMala** [comment]
Yeah, right now, it starts you at the center of the DF screen, so if you want to make sure you're in the air, make sure DF is looking at the surface before you start.

**Comment by JapaMala** [comment]
This feature has been deemed unfeasable.

If a developer with a VR headset wants to take this on, they're welcome to make their own fork.

**Comment by Wild-Dog** [comment]
How about now?
